---
- name: ensure legacy binaries are installed
  apt:
    update_cache: yes
    name:
      - iptables
      - arptables
      - ebtables
  notify: 
    - Switch to Legacy
- name: Enabling IPv4 forward
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward
- name: Enabling netfilter Kernel module
  shell: modprobe br_netfilter