---
- name: Creates Keyring directory if not exist
  file:
    path: /etc/apt/keyrings
    state: directory
    recurse: yes
- name: Remove existing ring file (if any)
  file:
    path: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: absent
- name: Adding Google Cloud package GPG key
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
- name: Adding Kubernetes repository with apt repository
  shell: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
- name: Remove Swap file
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disabling swap in order for the kubelet to work properly
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
- name: Installing Kubeadm and Kubelet
  apt:
    update_cache: yes
    name:
      - kubelet
      - kubeadm
  notify: 
    - Restart Kubelet