---
- name: Installing Containerd CE
  apt:
    update_cache: yes
    name:
      - containerd
- name: Downloading CriCtl 
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.28.0/crictl-v1.28.0-linux-amd64.tar.gz
    dest: /tmp/crictl.tar.gz
    mode: '0440'
- name: Installing CriCtl
  ansible.builtin.unarchive:
    src: /tmp/crictl.tar.gz
    dest: /usr/bin/
    remote_src: yes
- name: Creates containerd directory
  file:
    path: /etc/containerd
    state: directory
    recurse: yes
- name: Configuring runtime endpoint for crictl
  command: crictl config runtime-endpoint unix:///run/containerd/containerd.sock
- name: Generating Containerd Config
  command: containerd config default > /etc/containerd/config.toml
  notify: 
    - Restart Containerd